/*
 * opcao1.java
 *
 * Created on 18 de Agosto de 2006, 19:22
 */

package simple.modules.classificacao.paralelepipedo;


import java.awt.Color;
import java.util.List;


import simple.manipulacoes.imagem.Cor;
import simple.modules.classificacao.paralelepipedo.ClasseParalelepipedo;






/**
 *
 * @author  LUCIANA
 */
public class Legenda extends javax.swing.JFrame {
   
	private static final long serialVersionUID = 1L;
	List<ClasseParalelepipedo> classes;
	
    /**
     * Creates new form opcao1 
     */
    public Legenda(List<ClasseParalelepipedo> _classes) {
    	classes = _classes;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        opcaoLabel = new javax.swing.JLabel();
        rotulo = new javax.swing.JLabel();
        rotuloText1 = new javax.swing.JTextField();
        cor = new javax.swing.JLabel();
        corL1 = new javax.swing.JLabel();
        corL2 = new javax.swing.JLabel();
        corL3 = new javax.swing.JLabel();
        
        rotuloText2 = new javax.swing.JTextField();
        rotuloText3 = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classifica\u00e7\u00e3o - M\u00e9todo do paralelep\u00edpedo");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setResizable(false);
        getAccessibleContext().setAccessibleParent(this);
        opcaoLabel.setBorder(new javax.swing.border.TitledBorder("Legenda"));
        getContentPane().add(opcaoLabel);
        opcaoLabel.setBounds(20, 10, 270, 160);

        rotulo.setBackground(new java.awt.Color(102, 102, 255));
        rotulo.setFont(new java.awt.Font("Times New Roman", 0, 18));
        rotulo.setForeground(new java.awt.Color(255, 255, 255));
        rotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotulo.setText("R\u00f3tulo");
        rotulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        rotulo.setOpaque(true);
        getContentPane().add(rotulo);
        rotulo.setBounds(40, 40, 160, 20);
        
        rotuloText1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        rotuloText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rotuloText1.setBorder(null);
        rotuloText1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rotuloText1.setEnabled(false);
        getContentPane().add(rotuloText1);
        rotuloText1.setBounds(40, 70, 160, 20);
        rotuloText1.setBackground(Color.lightGray);

        cor.setBackground(new java.awt.Color(102, 102, 255));
        cor.setFont(new java.awt.Font("Times New Roman", 0, 18));
        cor.setForeground(new java.awt.Color(255, 255, 255));
        cor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cor.setText("Cor");
        cor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        cor.setOpaque(true);
        getContentPane().add(cor);
        cor.setBounds(210, 40, 50, 20);

        corL1.setBackground(Color.lightGray);
        corL1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        corL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corL1.setOpaque(true);
        getContentPane().add(corL1);
        corL1.setBounds(210, 70, 50, 20);

        corL2.setBackground(Color.lightGray);
        corL2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        corL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corL2.setOpaque(true);
        getContentPane().add(corL2);
        corL2.setBounds(210, 100, 50, 20);

        corL3.setBackground(Color.lightGray);
        corL3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        corL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corL3.setOpaque(true);
        getContentPane().add(corL3);
        corL3.setBounds(210, 130, 50, 20);

        rotuloText2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        rotuloText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rotuloText2.setBorder(null);
        rotuloText2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rotuloText2.setEnabled(false);
        getContentPane().add(rotuloText2);
        rotuloText2.setBounds(40, 100, 160, 20);
        rotuloText2.setBackground(Color.lightGray);

        rotuloText3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        rotuloText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rotuloText3.setBorder(null);
        rotuloText3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rotuloText3.setEnabled(false);
        getContentPane().add(rotuloText3);
        rotuloText3.setBounds(40, 130, 160, 20);
        rotuloText3.setBackground(Color.lightGray);


        if (classes.size() >= 1) {
        	rotuloText1.setText(classes.get(0).getRotulo());
        	rotuloText1.setBackground(Color.white);
        	Cor cor = classes.get(0).getCor();
        	Color color = new Color(cor.getCorR(), cor.getCorG(), cor.getCorB());
        	corL1.setBackground(color);
        }
        if (classes.size() >= 2) {
        	rotuloText2.setText(classes.get(1).getRotulo());
        	rotuloText2.setBackground(Color.white);
        	Cor cor = classes.get(1).getCor();
        	Color color = new Color(cor.getCorR(), cor.getCorG(), cor.getCorB());
        	corL2.setBackground(color);
        }
        if (classes.size() >= 3) {
        	rotuloText3.setText(classes.get(2).getRotulo());
        	rotuloText3.setBackground(Color.white);
        	Cor cor = classes.get(2).getCor();
        	Color color = new Color(cor.getCorR(), cor.getCorG(), cor.getCorB());
        	corL3.setBackground(color);
        }         
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-319)/2, (screenSize.height-218)/2, 319, 218);
    }

    private javax.swing.JLabel cor;
    private javax.swing.JLabel corL1;
    private javax.swing.JLabel corL2;
    private javax.swing.JLabel corL3;
    private javax.swing.JLabel opcaoLabel;
    private javax.swing.JLabel rotulo;
    private javax.swing.JTextField rotuloText1;
    private javax.swing.JTextField rotuloText2;
    private javax.swing.JTextField rotuloText3;
}
