/*
 * UNIVERSIDADE FEDERAL DE CAMPINA GRANDE
 * CENTRO DE ENGENHARIA ELÉTRICA E INFORMÁTICA
 * DEPARTAMENTO DE SISTEMAS E COMPUTAÇÃO
 * 
 * DISCIPLINA: PROCESSAMENTO DIGITAL DE IMAGENS
 * PROFESSOR: EUSTÁQUIO RANGEL
 * ALUNOS: LUCIANA CAVALCANTE DE MENEZES
 *         RICARDO MADEIRA FERNANDES
 * 
 * PROJETO: ILUSÕES DE ÓTICA.
 */
package ilusaoOticaNovo;

import facade.Facade;

import janelas.SImPLe;

import java.awt.AWTException;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;





/**
 * Classe responsável pela exibição da ilusão de ótica 1.
 * A ilusão 1 representa os 3 quadrados.
 * @author Luciana Cavalcante de Menezes.
 * @author Ricardo Madeira Fernandes.
 */
public class Ilusao1 extends JInternalFrame implements InternalFrameListener, MouseListener {

	/**
	 * Serial version.
	 */
	private static final long serialVersionUID = 1L;

	private JLabel quadrado1;

	private JLabel quadrado1_2;

	private JLabel quadrado1_3;

	private JLabel quadrado1_4;

	private JLabel quadrado1a;

	private JLabel quadrado2;

	private JLabel quadrado2_2;

	private JLabel quadrado2_3;

	private JLabel quadrado2_4;

	private JLabel quadrado2a;

	private JLabel quadrado3;

	private JLabel quadrado3_2;

	private JLabel quadrado3_3;

	private JLabel quadrado3_4;

	private JLabel quadrado3a;

	private JLabel titulo;

	private PaletaDeCores paletaDeCores;
	
	private SImPLe fepdi;
	
	private Facade facade;
	
	private String nome = "Ilus\u00e3o de Ótica";

	/**
	 * Cria uma nova instancia da ilusão de ótica 1.
	 */
	public Ilusao1(SImPLe fepdi, Facade facade) {
		addMouseListener(this);
		addInternalFrameListener(this);
		this.setFrameIcon(new ImageIcon("Resource/Icones/fepdi.JPG"));
		this.setClosable(true);
		this.setMaximizable(false);
		this.setResizable(false);
		
		this.fepdi = fepdi;
		this.facade= facade;
		
		initComponents();
		setFrameIcon(new ImageIcon("Resource/Icones/fepdi.JPG"));
		titulo.setSize(290,36);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	private void initComponents() {
		quadrado1a = new JLabel();
		quadrado1 = new JLabel();
		quadrado2a = new JLabel();
		quadrado2 = new JLabel();
		quadrado3a = new JLabel();
		quadrado3 = new JLabel();
		titulo = new JLabel();
		quadrado1_2 = new JLabel();
		quadrado1_3 = new JLabel();
		quadrado1_4 = new JLabel();
		quadrado2_2 = new JLabel();
		quadrado2_3 = new JLabel();
		quadrado2_4 = new JLabel();
		quadrado3_2 = new JLabel();
		quadrado3_3 = new JLabel();
		quadrado3_4 = new JLabel();

		getContentPane().setLayout(null);

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(nome);
		setBackground(new java.awt.Color(255, 255, 255));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setForeground(java.awt.Color.darkGray);
		setResizable(false);
		getAccessibleContext().setAccessibleParent(this);
		quadrado1a.setBackground(new java.awt.Color(204, 204, 204));
		quadrado1a.setFocusTraversalPolicyProvider(true);
		quadrado1a.setOpaque(true);
		quadrado1a.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado1aMouseClicked(evt);
			}
		});

		getContentPane().add(quadrado1a);
		quadrado1a.setBounds(60, 140, 100, 100);

		quadrado1.setBackground(new java.awt.Color(0, 0, 0));
		quadrado1.setFocusTraversalPolicy(quadrado1a.getFocusTraversalPolicy());
		quadrado1.setFocusTraversalPolicyProvider(true);
		quadrado1.setOpaque(true);
		quadrado1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado1MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado1);
		quadrado1.setBounds(20, 100, 180, 40);
		quadrado1.getAccessibleContext().setAccessibleName("quadrado1");

		quadrado2a.setBackground(new java.awt.Color(204, 204, 204));
		quadrado2a.setOpaque(true);
		quadrado2a.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado2aMouseClicked(evt);
			}
		});

		getContentPane().add(quadrado2a);
		quadrado2a.setBounds(250, 140, 100, 100);

		quadrado2.setBackground(new java.awt.Color(153, 153, 153));
		quadrado2.setOpaque(true);
		quadrado2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado2MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado2);
		quadrado2.setBounds(210, 100, 180, 40);

		quadrado3a.setBackground(new java.awt.Color(204, 204, 204));
		quadrado3a.setOpaque(true);
		quadrado3a.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado3aMouseClicked(evt);
			}
		});

		getContentPane().add(quadrado3a);
		quadrado3a.setBounds(440, 140, 100, 100);

		quadrado3.setBackground(new java.awt.Color(221, 218, 218));
		quadrado3.setOpaque(true);
		quadrado3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado3MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado3);
		quadrado3.setBounds(400, 100, 180, 40);

		paletaDeCores = new PaletaDeCores(this);

		titulo.setFont(new java.awt.Font("Tahoma", 1, 36));
		titulo.setText(nome);
		getContentPane().add(titulo);
		titulo.setBounds(160, 20, 270, 44);

		quadrado1_2.setBackground(new java.awt.Color(0, 0, 0));
		quadrado1_2.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado1_2.setFocusTraversalPolicyProvider(true);
		quadrado1_2.setOpaque(true);
		quadrado1_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado1_2MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado1_2);
		quadrado1_2.setBounds(20, 240, 180, 40);

		quadrado1_3.setBackground(new java.awt.Color(0, 0, 0));
		quadrado1_3.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado1_3.setFocusTraversalPolicyProvider(true);
		quadrado1_3.setOpaque(true);
		quadrado1_3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado1_3MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado1_3);
		quadrado1_3.setBounds(20, 130, 40, 120);

		quadrado1_4.setBackground(new java.awt.Color(0, 0, 0));
		quadrado1_4.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado1_4.setFocusTraversalPolicyProvider(true);
		quadrado1_4.setOpaque(true);
		quadrado1_4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado1_4MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado1_4);
		quadrado1_4.setBounds(160, 130, 40, 120);

		quadrado2_2.setBackground(new java.awt.Color(153, 153, 153));
		quadrado2_2.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado2_2.setFocusTraversalPolicyProvider(true);
		quadrado2_2.setOpaque(true);
		quadrado2_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado2_2MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado2_2);
		quadrado2_2.setBounds(210, 130, 40, 120);

		quadrado2_3.setBackground(new java.awt.Color(153, 153, 153));
		quadrado2_3.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado2_3.setFocusTraversalPolicyProvider(true);
		quadrado2_3.setOpaque(true);
		quadrado2_3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado2_3MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado2_3);
		quadrado2_3.setBounds(350, 130, 40, 120);

		quadrado2_4.setBackground(new java.awt.Color(153, 153, 153));
		quadrado2_4.setOpaque(true);
		quadrado2_4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado2_4MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado2_4);
		quadrado2_4.setBounds(210, 240, 180, 40);

		quadrado3_2.setBackground(new java.awt.Color(221, 218, 218));
		quadrado3_2.setOpaque(true);
		quadrado3_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado3_2MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado3_2);
		quadrado3_2.setBounds(400, 240, 180, 40);

		quadrado3_3.setBackground(new java.awt.Color(221, 218, 218));
		quadrado3_3.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado3_3.setFocusTraversalPolicyProvider(true);
		quadrado3_3.setOpaque(true);
		quadrado3_3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado3_3MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado3_3);
		quadrado3_3.setBounds(400, 130, 40, 120);

		quadrado3_4.setBackground(new java.awt.Color(221, 218, 218));
		quadrado3_4.setFocusTraversalPolicy(quadrado1a
				.getFocusTraversalPolicy());
		quadrado3_4.setFocusTraversalPolicyProvider(true);
		quadrado3_4.setOpaque(true);
		quadrado3_4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				quadrado3_4MouseClicked(evt);
			}
		});

		getContentPane().add(quadrado3_4);
		quadrado3_4.setBounds(540, 130, 40, 120);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 610) / 2, (screenSize.height - 421) / 2,
				610, 421);
	}

	private void quadrado3_2MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado3MouseClicked(evt);
	}

	private void quadrado3_4MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado3MouseClicked(evt);
	}

	private void quadrado3_3MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado3MouseClicked(evt);
	}

	private void quadrado2_4MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado2MouseClicked(evt);
	}

	private void quadrado2_3MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado2MouseClicked(evt);
	}

	private void quadrado2_2MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado2MouseClicked(evt);
	}

	private void quadrado1_3MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado1MouseClicked(evt);
	}

	private void quadrado1_2MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado1MouseClicked(evt);
	}

	private void quadrado1_4MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado1MouseClicked(evt);
	}

	private void quadrado3aMouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado3a.setBackground(paletaDeCores.getCorSelecionada());
	}

	private void quadrado3MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada()) {
			quadrado3.setBackground(paletaDeCores.getCorSelecionada());
			quadrado3_2.setBackground(paletaDeCores.getCorSelecionada());
			quadrado3_3.setBackground(paletaDeCores.getCorSelecionada());
			quadrado3_4.setBackground(paletaDeCores.getCorSelecionada());
		}
	}

	private void quadrado2aMouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado2a.setBackground(paletaDeCores.getCorSelecionada());
	}

	private void quadrado2MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada()) {
			quadrado2.setBackground(paletaDeCores.getCorSelecionada());
			quadrado2_2.setBackground(paletaDeCores.getCorSelecionada());
			quadrado2_3.setBackground(paletaDeCores.getCorSelecionada());
			quadrado2_4.setBackground(paletaDeCores.getCorSelecionada());
		}
	}

	private void quadrado1aMouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada())
			quadrado1a.setBackground(paletaDeCores.getCorSelecionada());
	}

	private void quadrado1MouseClicked(java.awt.event.MouseEvent evt) {
		if (paletaDeCores.isPinturaAtivada()) {
			quadrado1.setBackground(paletaDeCores.getCorSelecionada());
			quadrado1_2.setBackground(paletaDeCores.getCorSelecionada());
			quadrado1_3.setBackground(paletaDeCores.getCorSelecionada());
			quadrado1_4.setBackground(paletaDeCores.getCorSelecionada());
		}
	}
	
	public static JInternalFrame create(SImPLe fepdi, Facade facade){
		JInternalFrame ilusao =  new Ilusao1(fepdi,facade);
		ilusao.setVisible(true);
		
		return ilusao;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ilusao1(null,null).setVisible(true);
			}
		});
	}

	public void internalFrameActivated(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameClosed(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameClosing(InternalFrameEvent e) {
		fepdi.verificaUltimo();
		facade.decrementaPosicao();
		SImPLe.ilusao1.setEnabled(true);
	}

	public void internalFrameDeactivated(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameDeiconified(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameIconified(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameOpened(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseClicked(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
//		if (paletaDeCores.isPinturaAtivada()){
			try {
				fepdi.setCursor(Cursor.getSystemCustomCursor("Resource/Icones/cursor.gif"));
			} catch (HeadlessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (AWTException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
//		else fepdi.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//	}

	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mousePressed(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	public void mouseReleased(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

}
