/*
 * UNIVERSIDADE FEDERAL DE CAMPINA GRANDE
 * CENTRO DE ENGENHARIA ELÉTRICA E INFORMÁTICA
 * DEPARTAMENTO DE SISTEMAS E COMPUTAÇÃO
 * 
 * DISCIPLINA: PROCESSAMENTO DIGITAL DE IMAGENS
 * PROFESSOR: EUSTÁQUIO RANGEL
 * ALUNOS: LUCIANA CAVALCANTE DE MENEZES
 *         RICARDO MADEIRA FERNANDES
 * 
 * PROJETO: ILUSÕES DE ÓTICA.
 */

package simple.modules.propriedades.ilusaoOptica;


import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

import simple.ui.janelas.SImPLe;

import simple.facade.Facade;

/**
 * Classe responsável pela exibição da ilusão de ótica 2.
 * @author Luciana Cavalcante de Menezes.
 * @author Ricardo Madeira Fernandes.
 */
public class Ilusao2 extends JInternalFrame implements InternalFrameListener, MouseListener {
	
	/**
	 * Serial version.
	 */
	private static final long serialVersionUID = 1L;
	
	private PaletaDeCores paletaDeCores;
    private javax.swing.JLabel retanguloH10;
    private javax.swing.JLabel retanguloH11;
    private javax.swing.JLabel retanguloH2;
    private javax.swing.JLabel retanguloH3;
    private javax.swing.JLabel retanguloH4;
    private javax.swing.JLabel retanguloH5;
    private javax.swing.JLabel retanguloH6;
    private javax.swing.JLabel retanguloH7;
    private javax.swing.JLabel retanguloH8;
    private javax.swing.JLabel retanguloH9;
    private javax.swing.JLabel retanguloV1;
    private javax.swing.JLabel retanguloV10;
    private javax.swing.JLabel retanguloV11;
    private javax.swing.JLabel retanguloV12;
    private javax.swing.JLabel retanguloV13;
    private javax.swing.JLabel retanguloV14;
    private javax.swing.JLabel retanguloV15;
    private javax.swing.JLabel retanguloV16;
    private javax.swing.JLabel retanguloV17;
    private javax.swing.JLabel retanguloV18;
    private javax.swing.JLabel retanguloV19;
    private javax.swing.JLabel retanguloV2;
    private javax.swing.JLabel retanguloV20;
    private javax.swing.JLabel retanguloV21;
    private javax.swing.JLabel retanguloV22;
    private javax.swing.JLabel retanguloV23;
    private javax.swing.JLabel retanguloV24;
    private javax.swing.JLabel retanguloV3;
    private javax.swing.JLabel retanguloV4;
    private javax.swing.JLabel retanguloV5;
    private javax.swing.JLabel retanguloV6;
    private javax.swing.JLabel retanguloV7;
    private javax.swing.JLabel retanguloV8;
    private javax.swing.JLabel retanguloV9;
    private javax.swing.JLabel titulo;	
    
    private SImPLe fepdi;
	
	private Facade facade;
    
    private String nome = "Ilus\u00e3o de Ótica";
    
    /** Creates new form ilusao1 */
    public Ilusao2(SImPLe fepdi, Facade facade) {
    	addMouseListener(this);
		addInternalFrameListener(this);
		this.setFrameIcon(new ImageIcon("Resource/Icones/fepdi.JPG"));
		this.setClosable(true);
		this.setMaximizable(false);
		this.setResizable(false);
		
		this.fepdi = fepdi;
		this.facade= facade;
		
        initComponents();
        titulo.setSize(290,36);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {
        titulo = new JLabel();
        retanguloV1 = new JLabel();
        retanguloV2 = new JLabel();
        retanguloH2 = new JLabel();
        retanguloV11 = new JLabel();
        retanguloV3 = new JLabel();
        retanguloH5 = new JLabel();
        retanguloV17 = new JLabel();
        retanguloV18 = new JLabel();
        retanguloH4 = new JLabel();
        retanguloV16 = new JLabel();
        retanguloH3 = new JLabel();
        retanguloV4 = new JLabel();
        retanguloV5 = new JLabel();
        retanguloV6 = new JLabel();
        retanguloH6 = new JLabel();
        retanguloV19 = new JLabel();
        retanguloV7 = new JLabel();
        retanguloV8 = new JLabel();
        retanguloH7 = new JLabel();
        retanguloV12 = new JLabel();
        retanguloV9 = new JLabel();
        retanguloV13 = new JLabel();
        retanguloH10 = new JLabel();
        retanguloV22 = new JLabel();
        retanguloH9 = new JLabel();
        retanguloV20 = new JLabel();
        retanguloH8 = new JLabel();
        retanguloV21 = new JLabel();
        retanguloV14 = new JLabel();
        retanguloV23 = new JLabel();
        retanguloH11 = new JLabel();
        retanguloV15 = new JLabel();
        retanguloV24 = new JLabel();
        retanguloV10 = new JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(nome);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setResizable(false);
        getAccessibleContext().setAccessibleParent(this);
        
        paletaDeCores = new PaletaDeCores(this);
        
        titulo.setFont(new java.awt.Font("Tahoma", 1, 36));
        titulo.setText(nome);
        getContentPane().add(titulo);
        titulo.setBounds(160, 10, 270, 44);

        retanguloV1.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV1.setFocusTraversalPolicyProvider(true);
        retanguloV1.setOpaque(true);
        retanguloV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV1MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV1);
        retanguloV1.setBounds(90, 70, 30, 210);

        retanguloV2.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV2.setFocusTraversalPolicyProvider(true);
        retanguloV2.setOpaque(true);
        retanguloV2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV2MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV2);
        retanguloV2.setBounds(120, 70, 30, 90);

        retanguloH2.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH2.setFocusTraversalPolicyProvider(true);
        retanguloH2.setOpaque(true);
        retanguloH2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH2MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH2);
        retanguloH2.setBounds(120, 160, 30, 30);

        retanguloV11.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV11.setFocusTraversalPolicyProvider(true);
        retanguloV11.setOpaque(true);
        retanguloV11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV11MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV11);
        retanguloV11.setBounds(120, 190, 30, 90);

        retanguloV3.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV3.setFocusTraversalPolicyProvider(true);
        retanguloV3.setOpaque(true);
        retanguloV3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV3MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV3);
        retanguloV3.setBounds(150, 70, 30, 210);

        retanguloH5.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH5.setFocusTraversalPolicyProvider(true);
        retanguloH5.setOpaque(true);
        retanguloH5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH5MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH5);
        retanguloH5.setBounds(180, 220, 30, 30);

        retanguloV17.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV17.setFocusTraversalPolicyProvider(true);
        retanguloV17.setOpaque(true);
        retanguloV17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV17MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV17);
        retanguloV17.setBounds(180, 250, 30, 30);

        retanguloV18.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV18.setFocusTraversalPolicyProvider(true);
        retanguloV18.setOpaque(true);
        retanguloV18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV18MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV18);
        retanguloV18.setBounds(180, 190, 30, 30);

        retanguloH4.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH4.setFocusTraversalPolicyProvider(true);
        retanguloH4.setOpaque(true);
        retanguloH4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH4MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH4);
        retanguloH4.setBounds(180, 160, 30, 30);

        retanguloV16.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV16.setFocusTraversalPolicyProvider(true);
        retanguloV16.setOpaque(true);
        retanguloV16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV16MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV16);
        retanguloV16.setBounds(180, 130, 30, 30);

        retanguloH3.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH3.setFocusTraversalPolicyProvider(true);
        retanguloH3.setOpaque(true);
        retanguloH3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH3MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH3);
        retanguloH3.setBounds(180, 100, 30, 30);

        retanguloV4.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV4.setFocusTraversalPolicyProvider(true);
        retanguloV4.setOpaque(true);
        retanguloV4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV4MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV4);
        retanguloV4.setBounds(180, 70, 30, 30);

        retanguloV5.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV5.setFocusTraversalPolicyProvider(true);
        retanguloV5.setOpaque(true);
        retanguloV5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV5MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV5);
        retanguloV5.setBounds(210, 70, 30, 210);

        retanguloV6.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV6.setFocusTraversalPolicyProvider(true);
        retanguloV6.setOpaque(true);
        retanguloV6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV6MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV6);
        retanguloV6.setBounds(240, 70, 30, 90);

        retanguloH6.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH6.setFocusTraversalPolicyProvider(true);
        retanguloH6.setOpaque(true);
        retanguloH6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH6MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH6);
        retanguloH6.setBounds(240, 160, 30, 30);

        retanguloV19.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV19.setFocusTraversalPolicyProvider(true);
        retanguloV19.setOpaque(true);
        retanguloV19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV19MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV19);
        retanguloV19.setBounds(240, 190, 30, 90);

        retanguloV7.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV7.setFocusTraversalPolicyProvider(true);
        retanguloV7.setOpaque(true);
        retanguloV7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV7MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV7);
        retanguloV7.setBounds(270, 70, 30, 210);

        retanguloV8.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV8.setFocusTraversalPolicyProvider(true);
        retanguloV8.setOpaque(true);
        retanguloV8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV8MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV8);
        retanguloV8.setBounds(300, 70, 30, 210);

        retanguloH7.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH7.setFocusTraversalPolicyProvider(true);
        retanguloH7.setOpaque(true);
        retanguloH7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH7MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH7);
        retanguloH7.setBounds(330, 160, 30, 30);

        retanguloV12.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV12.setFocusTraversalPolicyProvider(true);
        retanguloV12.setOpaque(true);
        retanguloV12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV12MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV12);
        retanguloV12.setBounds(330, 190, 30, 90);

        retanguloV9.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV9.setFocusTraversalPolicyProvider(true);
        retanguloV9.setOpaque(true);
        retanguloV9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV9MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV9);
        retanguloV9.setBounds(330, 70, 30, 90);

        retanguloV13.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV13.setFocusTraversalPolicyProvider(true);
        retanguloV13.setOpaque(true);
        retanguloV13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV13MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV13);
        retanguloV13.setBounds(390, 70, 30, 30);

        retanguloH10.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH10.setFocusTraversalPolicyProvider(true);
        retanguloH10.setOpaque(true);
        retanguloH10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH10MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH10);
        retanguloH10.setBounds(390, 100, 30, 30);

        retanguloV22.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV22.setFocusTraversalPolicyProvider(true);
        retanguloV22.setOpaque(true);
        retanguloV22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV22MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV22);
        retanguloV22.setBounds(390, 130, 30, 30);

        retanguloH9.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH9.setFocusTraversalPolicyProvider(true);
        retanguloH9.setOpaque(true);
        retanguloH9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH9MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH9);
        retanguloH9.setBounds(390, 160, 30, 30);

        retanguloV20.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV20.setFocusTraversalPolicyProvider(true);
        retanguloV20.setOpaque(true);
        retanguloV20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV20MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV20);
        retanguloV20.setBounds(390, 190, 30, 30);

        retanguloH8.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH8.setFocusTraversalPolicyProvider(true);
        retanguloH8.setOpaque(true);
        retanguloH8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH8MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH8);
        retanguloH8.setBounds(390, 220, 30, 30);

        retanguloV21.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV21.setFocusTraversalPolicyProvider(true);
        retanguloV21.setOpaque(true);
        retanguloV21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV21MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV21);
        retanguloV21.setBounds(390, 250, 30, 30);

        retanguloV14.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV14.setFocusTraversalPolicyProvider(true);
        retanguloV14.setOpaque(true);
        retanguloV14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV14MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV14);
        retanguloV14.setBounds(420, 70, 30, 210);

        retanguloV23.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV23.setFocusTraversalPolicyProvider(true);
        retanguloV23.setOpaque(true);
        retanguloV23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV23MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV23);
        retanguloV23.setBounds(450, 190, 30, 90);

        retanguloH11.setBackground(new java.awt.Color(255, 0, 51));
        retanguloH11.setFocusTraversalPolicyProvider(true);
        retanguloH11.setOpaque(true);
        retanguloH11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloH11MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloH11);
        retanguloH11.setBounds(450, 160, 30, 30);

        retanguloV15.setBackground(new java.awt.Color(0, 51, 255));
        retanguloV15.setFocusTraversalPolicyProvider(true);
        retanguloV15.setOpaque(true);
        retanguloV15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV15MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV15);
        retanguloV15.setBounds(450, 70, 30, 90);

        retanguloV24.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV24.setFocusTraversalPolicyProvider(true);
        retanguloV24.setOpaque(true);
        retanguloV24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV24MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV24);
        retanguloV24.setBounds(480, 70, 30, 210);

        retanguloV10.setBackground(new java.awt.Color(255, 255, 102));
        retanguloV10.setFocusTraversalPolicyProvider(true);
        retanguloV10.setOpaque(true);
        retanguloV10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retanguloV10MouseClicked(evt);
            }
        });

        getContentPane().add(retanguloV10);
        retanguloV10.setBounds(360, 70, 30, 210);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-610)/2, (screenSize.height-421)/2, 610, 421);
    }

    private void retanguloH11MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())   
            mudaCorDosRetangulosVerticaisVermelhos();

    }
    
    private void  mudaCorDosRetangulosVerticaisVermelhos() {
        retanguloH2.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH3.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH4.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH5.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH6.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH7.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH8.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH9.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH10.setBackground(paletaDeCores.getCorSelecionada());
        retanguloH11.setBackground(paletaDeCores.getCorSelecionada());
    }
    private void retanguloH8MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH9MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH10MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH7MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH6MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH5MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH4MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH3MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloH2MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisVermelhos();

    }

    private void retanguloV24MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV14MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV10MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV8MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV19MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV6MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV17MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();
    }

    private void retanguloV18MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV16MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV4MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV11MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }

    private void retanguloV2MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAmarelos();

    }
    
    private void mudaCorDosRetangulosVerticaisAmarelos(){
        retanguloV2.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV11.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV4.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV16.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV18.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV17.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV6.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV19.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV8.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV10.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV14.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV24.setBackground(paletaDeCores.getCorSelecionada());
    }
    private void retanguloV23MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV15MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV20MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV21MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV22MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV13MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV12MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV9MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV7MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV5MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV3MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }

    private void retanguloV1MouseClicked(java.awt.event.MouseEvent evt) {
         if (paletaDeCores.isPinturaAtivada())        
            mudaCorDosRetangulosVerticaisAzuis();

    }
    
    private void mudaCorDosRetangulosVerticaisAzuis(){
        retanguloV1.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV3.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV5.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV7.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV9.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV12.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV22.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV13.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV20.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV21.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV15.setBackground(paletaDeCores.getCorSelecionada());
        retanguloV23.setBackground(paletaDeCores.getCorSelecionada());        
    }
    

	public static JInternalFrame create(SImPLe fepdi, Facade facade){
		JInternalFrame ilusao =  new Ilusao2(fepdi,facade);
		ilusao.setVisible(true);
		return ilusao;
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ilusao2(null,null).setVisible(true);
            }
        });
    }

	public void internalFrameActivated(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameClosed(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameClosing(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		fepdi.verificaUltimo();
		facade.decrementaPosicao();
		fepdi.closeIlusao(2);
	}

	public void internalFrameDeactivated(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameDeiconified(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameIconified(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void internalFrameOpened(InternalFrameEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

}
